version: "latest"
services:
  mysql:
    image: mysql
    container_name: Big_Bowl_Container       # name of container
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'big_bowl_db'           # name of database
      MYSQL_USER: 'user'                  # sample is the name of user
      MYSQL_PASSWORD: 'password'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: